name: Code Validation

on:
  pull_request:
    branches: [develop, master]

permissions:
  contents: read
  pull-requests: read

env:
  NODE_VERSION: '18'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend-changed: ${{ steps.changes.outputs.frontend }}
      backend-changed: ${{ steps.changes.outputs.backend }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            frontend:
              - 'frontend/**'
              - 'vite.config.ts'
              - 'package.json'
            backend:
              - 'backend/**'
              - 'gateway/**'
              - 'jest.config.ts'
              - 'tsconfig.json'
              - '.github/workflows/**'

  validate-backend:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.backend-changed == 'true' }}
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Instalar dependencias
        run: npm install

      - name: Typecheck y lint
        run: npm run verify

      - name: Tests (Jest)
        run: npm test

      - name: Compilar proyecto
        run: npm run build

  validate-frontend:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.frontend-changed == 'true' }}
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Instalar dependencias
        run: npm install

      - name: Build de frontend (Vite) y backend (tsc)
        run: npm run build

  notify-result:
    runs-on: ubuntu-latest
    needs: [detect-changes, validate-backend, validate-frontend]
    if: always()
    steps:
      - name: Notificar resultado
        run: |
          echo "=== VALIDACIÓN RESULTADO ==="
          echo "Frontend cambios: ${{ needs.detect-changes.outputs.frontend-changed }}"
          echo "Backend cambios: ${{ needs.detect-changes.outputs.backend-changed }}"
          echo "Backend validación: ${{ needs.validate-backend.result }}"
          echo "Frontend validación: ${{ needs.validate-frontend.result }}" 